### ISSUE TITLE
Feature request: Add screenshots / video to the VSCode marketplace!

### ISSUE THREAD

**Issue by LuminairPrime** [E-Jacques/pytestersuits#1]
Hello, your extension looks great! Without showing exactly what it does, it will be difficult for people to justify installing it. Add some screenshots or videos to get more clicks! :)

**Comment by E-Jacques** [comment]
Hello, thank for your interest !
I'm currently working on it, it takes time so it won't be available for all features right now.
Wish you a nice day !
